#!/bin/bash

echo "(gcc -o my-cat my-cat.c -Wall -Werror)"
gcc -o my-cat my-cat.c -Wall -Werror
echo "(gcc -o my-grep my-grep.c -Wall -Werror)"
gcc -o my-grep my-grep.c -Wall -Werror
echo "(gcc -o my-zip my-zip.c -Wall -Werror)"
gcc -o my-zip my-zip.c -Wall -Werror
echo "(gcc -o my-unzip my-unzip.c -Wall -Werror)"
gcc -o my-unzip my-unzip.c -Wall -Werror
echo "_______________________________________________________________________"
echo "TESTING MY-CAT"
echo ""
echo "TEST 1 NO INPUT FILE (./my-cat)"
./my-cat
echo ""
echo "TEST 2 CORRECT INPUT FILE (./my-cat oneline.txt)"
./my-cat oneline.txt
echo ""
echo "TEST 3 MULTIPLE INPUT FILES (./my-cat oneline.txt twolines.txt)"
./my-cat oneline.txt twolines.txt
echo ""
echo "TEST 4 INPUT FILE NOT FOUND (./my-cat thisIsNotFile.txt)"
./my-cat thisIsNotFile.txt
echo "_______________________________________________________________________"
echo "TESTING MY-GREP"
echo ""
echo "TEST 1 NO SEARCH STRING (./my-grep)"
./my-grep
echo ""
echo "TEST 2 NO INPUT FILE (./my-grep foo)"
./my-grep foo
echo ""
echo "TEST 3 MATCH ALL STDIN (./my-grep '')"
./my-grep ""
echo ""
echo "TEST 4 NORMAL USE WITH SINGLE FILE (./my-grep first twolines.txt)"
./my-grep first twolines.txt
echo ""
echo "TEST 5 MATCH ALL IN FILE (./my-grep '' twolines.txt)"
./my-grep "" twolines.txt
echo ""
echo "TEST 6 CASE SENSITIVE NORMAL USE (./my-grep First twolines.txt)"
./my-grep First twolines.txt
echo ""
echo "TEST 7 MULTIPLE FILES NORMAL USE (./my-grep first oneline.txt twolines.txt)"
./my-grep first oneline.txt twolines.txt
echo ""
echo "TEST 8 MATCH ALL IN MULTIPLE FILES (./my-grep '' oneline.txt twolines.txt)"
./my-grep '' oneline.txt twolines.txt
echo ""
echo "TEST 9 INPUT FILE NOT FOUND (./my-grep foo thisIsNotFile.txt)"
./my-grep foo thisIsNotFile.txt
echo "_______________________________________________________________________"
echo "TESTING MY-ZIP"
echo ""
echo "TEST 1 NO INPUT FILE (./my-zip)"
./my-zip
echo ""
echo "TEST 2 NORMAL USE NO REDIRECTION (./my-zip oneline.txt)"
./my-zip oneline.txt
echo ""
echo "TEST 3 NORMAL USE REDIRECT TO FILE (./my-zip oneline.txt > file.z)"
./my-zip oneline.txt > file.z
echo ""
echo "TEST 4 MULTIPLE FILE NORMAL USE WITH REDIRECT (./my-zip oneline.txt twolines.txt > file2.z)"
./my-zip oneline.txt twolines.txt > file2.z
echo ""
echo "TEST 5 INPUT FILE NOT FOUND (./my-zip thisIsNotFile.txt)"
./my-zip thisIsNotFile.txt
echo "_______________________________________________________________________"
echo "TESTING MY-UNZIP, USING FILES ZIPPED IN LAST PART"
echo ""
echo "TEST 1 NO INPUT FILE (./my-unzip)"
./my-unzip
echo ""
echo "TEST 2 NORMAL USE SINGLE FILE (./my-unzip file.z)"
./my-unzip file.z
echo ""
echo "TEST 3 NORMAL USE MULTIPLE FILE (./my-unzip file.z file2.z)"
./my-unzip file.z file2.z
echo ""
echo "TEST 4 INPUT FILE NOT FOUND (./my-unzip thisIsNotFile.z)"
./my-unzip thisIsNotFile.z
echo ""
echo "TESTING DONE"